variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: EasyTravelAngular

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: EasyTravelAngular

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'EasyTravelAngular/dist'